---
title: Help a Jew. Help the Holy Land
timezone: UTC
collections:
  guide:
    title: Guides
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:year/:month/:day/:title"
    author: Sophia Tupolev
- scope:
    path: ''
    type: guide
  values:
    layout: guide
    permalink: "/guide/:title"
    thumbnail_image: ''
description: "<em>Help a Jew. Help the Holy Land</em> is a group of dedicated legal
  professionals who want to help those who have been denied their right to return
  to the Holy Land"
url: http://haj.siteleaf.net
email: fkolesnik@gmail.com
linkedin: "//linkedin.com"
twitter: "//twitter.com"
facebook: "//facebook.com"
phone: "+972 54 555 55 55"
address: 25 Mashukaze Street<br/>Tel Aviv-Yafo, 1231234<br/>Israel
permalink: "/:title/"
image-placeholder: assets/img/placeholder.png
excerpt_separator: "<!--more-->"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- ".idea"
- ".sass-cache"
