title: Help a Jew. Help the Holy Land
description: > # this means to ignore newlines until "baseurl:"
  “Help a Jew Help the Holy Land” is a group of dedicated legal professionals who want
  to help those who have been denied their right to return to the Holy Land
baseurl: /haj
url: "https://fkolesnik.github.io/haj"
email: name@domain.com
instagram: "//instagram.com"
twitter: "//twitter.com"
facebook: "//facebook.com"
phone: +972 54 555 55 55
address: '25 Mashukaze Street<br/>Tel Aviv-Yafo, 1231234<br/>Israel'


# Build settings

permalink: /:title
image-placeholder: 'assets/img/placeholder.png'
image-placeholder-2: 'assets/img/placeholder-2.png'
excerpt_separator: <!--more-->

markdown: kramdown

gems:
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package.json
    - .idea




